packages:
  - billing
  - carpark
  - filecoin
  - indexer
  - psa
  - replicator
  - roundabout
  - tools
  - upload-api

catalog:
  "@aws-sdk/client-dynamodb": 3.563.0
  "@aws-sdk/client-eventbridge": 3.563.0
  "@aws-sdk/client-glue": 3.563.0
  "@aws-sdk/client-kinesis": 3.563.0
  "@aws-sdk/client-s3": 3.563.0
  "@aws-sdk/client-sqs": 3.563.0
  "@aws-sdk/s3-request-presigner": 3.563.0
  "@aws-sdk/util-dynamodb": 3.563.0
  "@babel/cli": ^7.23.0
  "@babel/core": ^7.23.3
  "@babel/preset-react": ^7.23.3
  "@chainsafe/libp2p-noise": ^15.0.0
  "@dsnp/parquetjs": ^1.8.6
  "@helia/unixfs": ^3.0.6
  "@ipld/car": ^5.4.0
  "@ipld/dag-cbor": ^9.2.2
  "@ipld/dag-json": ^10.2.3
  "@ipld/dag-pb": ^4.1.3
  "@ipld/dag-ucan": ^3.4.5
  "@libp2p/identify": ^2.0.1
  "@libp2p/mplex": ^10.0.23
  "@libp2p/websockets": ^8.0.23
  "@multiformats/multiaddr": ^12.2.1
  "@octokit/types": ^13.8.0
  "@sentry/serverless": ^7.74.1
  "@storacha/access": ^1.6.0
  "@storacha/blob-index": ^1.2.0
  "@storacha/capabilities": ^1.8.0
  "@storacha/client": ^1.7.2
  "@storacha/did-mailto": ^1.0.2
  "@storacha/filecoin-api": ^1.1.11
  "@storacha/filecoin-client": ^1.0.10
  "@storacha/indexing-service-client": ^2.5.0
  "@storacha/one-webcrypto": ^1.0.1
  "@storacha/upload-api": ^2.2.0
  "@storacha/upload-client": ^1.3.1
  "@tsconfig/node16": ^1.0.3
  "@types/aws-lambda": ^8.10.108
  "@types/big.js": ^6.2.1
  "@types/express": ^5.0.1
  "@types/git-rev-sync": ^2.0.0
  "@types/reload": ^3.2.3
  "@ucanto/client": ^9.0.1
  "@ucanto/core": ^10.4.0
  "@ucanto/interface": ^10.3.0
  "@ucanto/principal": ^9.0.2
  "@ucanto/server": ^10.2.0
  "@ucanto/transport": ^9.2.0
  "@ucanto/validator": ^9.1.0
  "@web-std/blob": ^3.0.5
  "@web-std/fetch": ^4.1.0
  "@web-std/stream": ^1.0.3
  "@web3-storage/content-claims": ^5.2.1
  "@web3-storage/content-claims-infra": ^1.2.1
  "@web3-storage/data-segment": ^5.3.0
  "@web3-storage/sigv4": ^1.0.2
  "@web3-storage/upload-api": ^19.1.0
  ava: ^4.3.3
  aws-cdk-lib: 2.179.0
  aws-lambda: ^1.0.7
  aws-lambda-test-utils: ^1.3.0
  big.js: ^6.2.1
  c8: ^8.0.1
  chalk: 4.1.2
  concurrently: ^8.2.2
  csv-parser: ^3.0.0
  csv-stringify: ^6.4.6
  delay: ^6.0.0
  dotenv: ^16.4.5
  entail: ^2.1.2
  esbuild: ^0.23.1
  eslint: ^8.57.0
  express: ^4.19.2
  fr32-sha2-256-trunc254-padded-binary-tree-multihash: ^3.3.0
  git-rev-sync: ^3.0.2
  hd-scripts: ^3.0.2
  helia: ^4.2.1
  libp2p: 1.5.2
  lint-staged: ^13.0.3
  lru-cache: ^11.0.0
  mailslurp-client: ^15.17.2
  multiformats: ^13.3.2
  nanoid: ^5.1.5
  nodemon: ^3.1.4
  p-all: ^5.0.0
  p-defer: ^4.0.0
  p-map: ^7.0.2
  p-retry: ^6.2.1
  p-queue: ^8.0.1
  p-wait-for: ^5.0.0
  preact: ^10.14.1
  preact-render-to-string: ^6.2.2
  prom-client: ^15.0.0
  reload: ^3.3.0
  sade: ^1.8.1
  sqs-consumer: ^7.4.0
  sst: 2.48.5
  stripe: ^14.2.0
  testcontainers: ^10.7.1
  typescript: ^5.5.4
  uint8arrays: ^5.1.0
