/**
 * SST Config type declarations.
 *
 * These types are normally auto-generated by SST when running `sst dev` or `sst build`.
 * We declare them here to allow TypeScript to compile before deployment.
 *
 * Note: After running `sst build`, this file will be overwritten with the actual
 * generated types based on your Config.Parameter and Config.Secret definitions.
 */

import "sst/node/config";

declare module "sst/node/config" {
  export interface ParameterResources {
    AGGREGATOR_DID: {
      value: string
    }
    CONTENT_CLAIMS_DID: {
      value: string
    }
    CONTENT_CLAIMS_URL: {
      value: string
    }
    INDEXING_SERVICE_DID: {
      value: string
    }
    INDEXING_SERVICE_URL: {
      value: string
    }
    DEAL_TRACKER_DID: {
      value: string
    }
    DEAL_TRACKER_URL: {
      value: string
    }
    POSTMARK_TOKEN: {
      value: string
    }
    PROVIDERS: {
      value: string
    }
    R2_ENDPOINT: {
      value: string
    }
    R2_ACCESS_KEY_ID: {
      value: string
    }
    R2_SECRET_ACCESS_KEY: {
      value: string
    }
    R2_REGION: {
      value: string
    }
    R2_CARPARK_BUCKET: {
      value: string
    }
    R2_DELEGATION_BUCKET: {
      value: string
    }
  }
}
