import * as UCAN from '@ipld/dag-ucan'

export interface UcanInvocation {
  att: UCAN.Capabilities
  aud: `did:${string}:${string}`
  iss: `did:${string}:${string}`
  prf: string[]
}

export interface UcanInvocationWrapper {
  carCid: string
  bytes: Uint8Array
  value: UcanInvocation
}

// would be generated by sst, but requires `sst build` to be run, which calls out to aws; not great for CI
declare module '@serverless-stack/node/config' {
  export interface SecretResources {
    PRIVATE_KEY: {
      value: string
    },
    UCAN_INVOCATION_POST_BASIC_AUTH: {
      value: string
    }
  }
}

export {}
