import type {
  Failure,
  Link,
  Invocation,
  ServiceMethod,
} from '@ucanto/interface'
import type { API } from '@ucanto/server'

import {
  StoreAdd,
  StoreRemove,
  StoreList,
  UploadAdd,
  UploadRemove,
  UploadList
} from '@web3-storage/access/capabilities/types'

export interface Service {
  store: {
    add: ServiceMethod<StoreAdd, StoreAddResult, Failure>,
    remove: ServiceMethod<StoreRemove, void, Failure>,
    list: ServiceMethod<StoreList, ListResponse<StoreListResult>, Failure>,
  },
  upload: {
    add: ServiceMethod<UploadAdd, UploadAddResult, Failure>,
    remove: ServiceMethod<UploadRemove, void, Failure>,
    list: ServiceMethod<UploadList, ListResponse<UploadItemOutput>, Failure>,
  }
}

export interface StoreServiceContext {
  storeTable: StoreTable,
  carStoreBucket: CarStoreBucket,
  signer: Signer
  access: AccessClient
}

export interface UcantoServerContext extends StoreServiceContext, UploadServiceContext {}

export interface UploadServiceContext {
  uploadTable: UploadTable
}

export interface CarStoreBucket {
  has: (key: string) => Promise<boolean>
}

export interface StoreTable {
  exists: (space: string, car: string) => Promise<boolean>
  insert: (item: StoreItemInput) => Promise<StoreItemOutput>
  remove: (space: string, car: string) => Promise<void>
  list: (space: string, options?: ListOptions) => Promise<ListResponse<StoreListResult>>
}

export interface UploadTable {
  exists: (space: string, root: string) => Promise<boolean>
  insert: (item: UploadItemInput) => Promise<UploadItemOutput[]>
  remove: (space: string, root: string) => Promise<void>
  list: (space: string, options?: ListOptions) => Promise<ListResponse<UploadItemOutput>>
}

export interface Signer {
  sign: (link: Link<unknown, number, number, 0 | 1>) => { url: URL, headers: Record<string, string>}
}

export interface StoreItemInput {
  space: string,
  car: string,
  size: number,
  origin?: string,
  agent: string,
  ucan: string,
}

export interface StoreItemOutput extends StoreItemInput {
  insertedAt: string,
}

export interface StoreAddResult {
  status: 'upload' | 'done',
  with: API.URI<"did:">,
  link: API.Link<unknown, number, number, 0 | 1>,
  url?: URL,
  headers?: Record<string, string>
}

export interface ListOptions {
  size?: number,
  cursor?: string
}

export interface StoreListResult {
  car: string
  size: number
  origin?: string
  insertedAt: string
}

export interface ListResponse<R> {
  cursor?: string,
  size: number,
  results: R[]
}

interface UploadItemBase {
  space: string
  root: string,
  agent: string,
  ucan: string,  
}

export interface UploadItemInput extends UploadItemBase {
  shards: string[]
}

export interface UploadItemOutput extends UploadItemBase {
  shard: string,
  insertedAt: string,
}

export interface AccessClient {
  /**
   * Determines if the issuer of the invocation has received a delegation
   * allowing them to issue the passed invocation.
   */
  verifyInvocation: (invocation: Invocation) => Promise<boolean>
}

export interface UploadAddResult extends Array<UploadItemOutput> {}

// would be generated by sst, but requires `sst build` to be run, which calls out to aws; not great for CI
declare module "@serverless-stack/node/config" {
  export interface SecretResources {
    "PRIVATE_KEY": {
      value: string;
    }
  }
}
