name: Fetch metrics for Space

on:
  workflow_dispatch:
    inputs:
      space_did:
        required: true
        description: DID of the space
        type: string
      env:
        required: true
        description: The env to fetch metrics against. Default is production.
        options: 
          - staging
          - production
        default: production

jobs:
  fetch-metrics-for-space:
    name: Fetch metrics for Space
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: Run job
        env:
          DEBUG: '*'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ENV: ${{ github.event.inputs.env }}
          SPACE_DID:  ${{ github.event.inputs.space_did }}
          TABLE_NAME: 'space-metrics'
        run: npm run fetch-metrics-for-space
